### ISSUE TITLE
您好，我在读取数据遇到了IndexError: too many indices for array的问题

### ISSUE THREAD

**Issue by userpei** [ltguo19/VSUA-Captioning#9]
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    train(opt)
  File "train.py", line 76, in train
    data = loader.get_batch('train')
  File "VSUA-Captioning-master/dataloader.py", line 144, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "VSUA-Captioning-master/dataloader.py", line 368, in get
    tmp = self.split_loader.next()
  File "/home/usr2/anaconda2//lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/usr2/anaconda2/envs/pyx/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/usr2/anaconda2//lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/VSUA-Captioning-master/dataloader.py", line 253, in __getitem__
    sg_data = self.get_graph_data(index)
  File "/VSUA-Captioning-master/dataloader.py", line 277, in get_graph_data
    rela['edges'] = triplet[:, 0:2]
IndexError: too many indices for array

**Comment by kkunli** [comment]
您好，我也在使用semantic relationship时遇到了这个问题，请问解决了吗？

**Comment by userpei** [comment]
> 您好，我也在使用semantic relationship时遇到了这个问题，请问解决了吗？

        if sg_use['rela_matrix'].shape[0] == 0:
            sg_use['rela_matrix'] = np.array([[0, 0, self.sg_vocab['near']]], dtype=sg_use['rela_matrix'].dtype)
修改之后，没有报错了

**Comment by kkunli** [comment]
修改后迭代几次,还是报错,您没发生这个问题吗?

KeyError: 'Traceback (most recent call last):\n  File "/home/b604_1/anaconda2/envs/pyli2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/b604_1/aaa/VSUA-Captioning/dataloader.py", line 253, in __getitem__\n    sg_data = self.get_graph_data(index)\n  File "/home/b604_1/aaa/VSUA-Captioning/dataloader.py", line 270, in get_graph_data\n    sg_use[\'rela_matrix\'] = np.array([[0, 0, self.sg_vocab[\'near\']]], dtype=sg_use[\'rela_matrix\'].dtype)\nKeyError: \'near\'\n'
